// Curated narrative text for each featured neighborhood.
// Each entry has text for 4 deep-dive steps (affordability+rent merged, ownership, eviction, what's left).
export const stories = {
  'Dorchester': {
    rentAndAffordability: `Dorchester is Boston's largest rental market — nearly 2,000 properties in our dataset, dominated by the iconic triple-decker. In 2016, ZORI tracked rents here at <strong>$2,329/mo</strong>. Today they've hit <strong>$3,123</strong> — a <strong>34% increase</strong>. At a $2,500 budget, <strong>1,587 units</strong> that were once affordable have been priced out.`,
    ownership: `66% of rental purchases here are by investors — lower than the citywide average, reflecting Dorchester's deep roots in owner-occupied multi-family housing. But that's changing. Two- and three-family homes that families owned for generations are being sold to LLCs. Corporate ownership stands at 15.7%, while owner-occupancy has fallen to 42.5%.`,
    eviction: `Dorchester leads Boston in raw eviction filings: <strong>2,035 cases</strong> between 2020 and 2024 — nearly a third of all filings citywide. 59% come from corporate landlords. The dominant type is <strong>non-payment of rent</strong> (1,344 cases), reflecting a community where renter incomes ($29,739 median) simply can't keep pace with rising costs.`,
    whatsLeft: `Dorchester's triple-decker neighborhoods are the front line of Boston's affordability crisis. The sheer scale — almost 2,000 rental properties — means what happens here shapes the city. And right now, affordable units are vanishing fast.`,
  },
  'Roxbury': {
    rentAndAffordability: `Roxbury has experienced one of Boston's most dramatic rent surges: <strong>+68%</strong> since 2016, from $2,233 to $3,757/mo. With a renter median income of just <strong>$23,499</strong>, that means the average rent now exceeds what a typical renter earns in a month. Every unit that was affordable at $2,500 is now gone.`,
    ownership: `75% of rental purchases in Roxbury are by investors, and corporate ownership is at 19.7%. But what makes Roxbury's story distinct is the <strong>severity of displacement pressure on extremely low incomes</strong>. Owner-occupancy has dropped to 34.3%. The community that built Roxbury is being priced out of it.`,
    eviction: `59% of all properties in our dataset have an eviction flag — the <strong>highest rate in Boston</strong>. Of the 553 filings, <strong>76% come from corporate landlords</strong>. Post-eviction, ZORI data shows rents in Roxbury jump 8.6% — the largest post-eviction rent increase of any neighborhood, confirming that eviction is being used as a profit strategy.`,
    whatsLeft: `Roxbury tells the starkest story in Boston: a low-income community where rents have nearly doubled, evictions are rampant, and corporate landlords capture the largest post-eviction rent gains in the city. What was once affordable here no longer exists at moderate budgets.`,
  },
  'Mission Hill': {
    rentAndAffordability: `Mission Hill has seen the <strong>steepest rent increase in Boston: +84%</strong>, from $2,672 to $4,920/mo. Its proximity to the Longwood Medical Area has made it a magnet for investment. With 90% investor ownership and a renter median income of just $24,683, the average rent is now <strong>2.4x what a typical renter earns monthly</strong>. Even at a $2,500 budget, there was nothing affordable here to begin with.`,
    ownership: `This is near-total investor dominance: <strong>90% of rental purchases are by investors</strong>, the highest of any featured neighborhood. Corporate ownership is at 22.4% and owner-occupancy has collapsed to just 19.9%. Mission Hill has essentially become an investor-owned rental district adjacent to the medical campus.`,
    eviction: `Despite the extreme investor presence, eviction filings (131) are moderate — the <strong>eviction flag rate is just 31%</strong>. This suggests Mission Hill's displacement happens differently: through <strong>lease non-renewals and steep rent increases</strong> rather than court filings. When rents nearly double, tenants leave before eviction is necessary.`,
    whatsLeft: `Mission Hill is a case study in how investor concentration near an employment hub can transform a neighborhood. The 84% rent surge has made it one of Boston's most expensive rental markets — a dramatic shift for what was once a working-class area.`,
  },
  'Beacon Hill': {
    rentAndAffordability: `Beacon Hill's rents have risen 33% since 2016, from $2,495 to $3,323/mo. But unlike lower-income neighborhoods, its renter population can absorb it — the median renter income here is <strong>$67,084</strong>, the highest in Boston. Affordability isn't the crisis in Beacon Hill; <strong>corporate control</strong> is.`,
    ownership: `<strong>98% of rental purchases are by investors</strong> — virtually no individual buyers. The rental market is almost entirely corporate-controlled. Yet corporate ownership on the census measure is just 20%, suggesting these are sophisticated entities (trusts, LLCs, holding companies) that don't always register as "corporate" in tax records.`,
    eviction: `Here is where Beacon Hill stands out: <strong>98% of all eviction filings come from corporate landlords</strong> — the second-highest rate in Boston. Yet the overall eviction rate is just 16%. Corporate landlords here are selective and efficient. When they do evict, it's almost always institutional — individual landlords are essentially absent from the displacement picture.`,
    whatsLeft: `Beacon Hill shows that corporate takeover happens even in wealthy neighborhoods. The difference is the mechanism: not poverty-driven displacement, but total institutional control of the rental market. The handful of evictions that occur are almost all corporate.`,
  },
  'Chinatown': {
    rentAndAffordability: `Chinatown is small but the pressure is immense. Rents have climbed 21% to $3,703/mo — in a community where the median renter earns just <strong>$15,484/year</strong>. That means a single month's average rent equals <strong>nearly 3 months of income</strong>. This is the most extreme rent burden in Boston.`,
    ownership: `With only 23 rental properties in our dataset, Chinatown's story is about <strong>concentration of power</strong>. 96% of purchases are by investors. Every property transaction reshapes this tiny neighborhood. Corporate ownership is 22.9% — but in a community this small, a few corporate landlords can control the entire rental market.`,
    eviction: `<strong>100% of eviction filings in Chinatown come from corporate landlords</strong> — the only neighborhood in Boston with this distinction. All 67 cases were brought by institutional entities. 52% of properties in our data have an eviction flag. In a community of this size, each eviction ripples through the entire neighborhood.`,
    whatsLeft: `Chinatown is the extreme case: the most rent-burdened, the most corporate-controlled, and the only neighborhood where every single eviction is filed by a corporation. Its small size makes it both the most vulnerable and the most visible example of what corporate landlord dominance looks like.`,
  },
  'East Boston': {
    rentAndAffordability: `East Boston has seen a <strong>68% rent increase</strong> — from $1,826 to $3,071/mo — one of the largest jumps in the city. What was once one of Boston's most reliably affordable entry points for immigrant families has rapidly priced out its community. At $2,500/mo, <strong>641 units</strong> that were affordable are now gone.`,
    ownership: `79% of rental purchases are by investors. Corporate ownership surged from 3% in 2004 to 25% today — a <strong>more than 8x increase</strong> in 20 years. East Boston's three-family homes (438 in our data, the dominant type) are the primary target: affordable enough to acquire, profitable enough to convert.`,
    eviction: `318 eviction filings, with 65% from corporate landlords — lower than the citywide corporate rate, reflecting that <strong>individual landlords still play a significant role here</strong>. East Boston's active tenant organizing movement has pushed back against displacement, but the economic pressures continue to mount as rents climb.`,
    whatsLeft: `East Boston is the transformation story: an immigrant neighborhood where corporate ownership exploded 8x in 20 years, rents nearly doubled, and 641 affordable units vanished. The community organizing here is among Boston's strongest — but the numbers show the scale of what they're fighting.`,
  },
  'Hyde Park': {
    rentAndAffordability: `Hyde Park remains one of Boston's last affordable holdouts. Rents have risen 29%, from $2,039 to $2,635/mo — significant, but still among the lowest in the city. At $2,500/mo, 149 units were affordable. Today, even Hyde Park has been priced past that threshold.`,
    ownership: `Hyde Park stands apart: only <strong>47% investor purchases</strong> — the lowest of any featured neighborhood. Owner-occupancy is <strong>57.4%</strong>, the highest in Boston. Corporate ownership is just 9.3%. This is what a neighborhood looks like before the corporate wave fully arrives. Two-family homes (224 properties) define the housing stock — traditional owner-occupied duplexes.`,
    eviction: `Despite low corporate ownership, Hyde Park has <strong>488 eviction filings</strong> — more than many wealthier neighborhoods. 74% are from corporate filers, and <strong>80% are for non-payment of rent</strong>. This tells a different story than Beacon Hill or Chinatown: evictions here are driven by <strong>economic hardship</strong>, not corporate displacement strategy.`,
    whatsLeft: `Hyde Park is the bellwether. With the lowest investor rate and highest owner-occupancy, it shows what Boston neighborhoods looked like before the corporate takeover. The question is whether it can hold. Rising rents and a growing investor presence suggest the pressure is building.`,
  },
  'South End': {
    rentAndAffordability: `The South End's transformation is well underway. Rents have climbed 51%, from $2,620 to $3,959/mo. Once a diverse, affordable neighborhood, it now commands some of Boston's highest rents. The housing stock tells the story: <strong>435 of 523 properties are condos</strong> — the traditional multi-family homes have largely been converted.`,
    ownership: `<strong>98% of rental purchases are by investors</strong>, matching Beacon Hill for the most corporate-dominated market in Boston. Corporate ownership is 25.3% — the highest of any featured neighborhood. Owner-occupancy has fallen to 30.7%. The South End's brownstones are now investment vehicles.`,
    eviction: `433 eviction filings, with <strong>88% from corporate landlords</strong>. The dominant case type is non-payment of rent (334 cases). With 42% of properties flagged for eviction, the South End shows the full cycle: corporate acquisition, rent increases, and displacement of tenants who can't keep up.`,
    whatsLeft: `The South End is the completed gentrification story. From brownstone boarding houses to luxury condos, the neighborhood has been remade by institutional capital. What remains affordable here is negligible — a transformation that took less than two decades.`,
  },
};
