import * as d3 from 'd3'

// ── ZIP metadata ─────────────────────────────────────────────────────────────
// Top 5 ZIPs by 2023 condo conversions (from EDA)

export const TOP_ZIPS = ['02127', '02131', '02130', '02136', '02128']

export const ZIP_NAMES = {
  '02108': 'Downtown',
  '02109': 'North End',
  '02110': 'Financial District',
  '02111': 'Chinatown',
  '02113': 'North End',
  '02114': 'Beacon Hill',
  '02115': 'Fenway',
  '02116': 'Back Bay',
  '02118': 'South End',
  '02119': 'Roxbury',
  '02120': 'Mission Hill',
  '02121': 'Dorchester',
  '02122': 'Dorchester',
  '02124': 'Dorchester',
  '02125': 'Dorchester',
  '02126': 'Mattapan',
  '02127': 'South Boston',
  '02128': 'East Boston',
  '02129': 'Charlestown',
  '02130': 'Jamaica Plain',
  '02131': 'Roslindale',
  '02132': 'West Roxbury',
  '02134': 'Allston',
  '02135': 'Brighton',
  '02136': 'Hyde Park',
}

// Colors: top 5 ZIPs highlighted, rest gray
export const ZIP_COLORS = {
  '02127': '#e74c3c',  // South Boston — red
  '02131': '#e67e22',  // Roslindale — orange
  '02130': '#e91e8c',  // Jamaica Plain — pink
  '02136': '#c8b400',  // Hyde Park — gold
  '02128': '#8e44ad',  // East Boston — purple
  other:   '#3a3a3a',  // all other ZIPs — dark gray
}

// ── Key stats (from EDA — for use in narrative text) ─────────────────────────
export const STATS = {
  total_conversions_2016_2024: 2245,
  total_new_units:             10118,
  conversions_2023:            868,
  estimated_displaced:         22259,
  avg_value_jump_pct:          0.406,   // +40.6% property value after conversion
  top_zip_2023:                '02127', // South Boston
}

// ── Map data loaders ──────────────────────────────────────────────────────────

/**
 * Loads neighborhood GeoJSON with metrics merged in.
 * Generated by fp2_preprocess.py — run that first.
 *
 * Each feature.properties:
 *   name                   — neighborhood name (string)
 *   avg_monthly_payment    — average naive monthly payment (integer, dollars)
 *   median_monthly_payment — median monthly payment
 *   p25_payment            — 25th percentile
 *   p75_payment            — 75th percentile
 *   parcel_count           — number of parcels in sample
 *   total_evictions        — total evictions 2020–2023
 *   avg_corp_own_rate      — average corporate ownership rate (0–1)
 *   avg_own_occ_rate       — average owner-occupancy rate (0–1)
 *   avg_renter_mhi         — average renter median household income
 */
export async function loadNeighborhoodGeo() {
  return d3.json('./data/neighborhoods.geojson')
}

/**
 * Loads sampled parcel scatter points.
 * Each item: { neighborhood, lng, lat, monthly_payment }
 */
export async function loadParcelSample() {
  return d3.json('./data/parcels_sample.json')
}

// ── Color scales (Andrew's Visual Design Study palette) ───────────────────────

/**
 * Choropleth color scale for monthly housing payment.
 * Bins: [0–2000, 2000–3000, 3000–4000, 4000–5000, 5000+]
 * Uses Housing Transition palette (yellow → deep orange).
 */
export function makePaymentColorScale() {
  return d3.scaleThreshold()
    .domain([2000, 3000, 4000, 5000])
    .range(['#f4e4a8', '#f0c860', '#e09030', '#d4730a', '#9a4e00'])
}

/**
 * Color scale for corporate ownership rate (0–1).
 * Uses Investor Activity palette (light teal → deep teal).
 */
export function makeCorpOwnColorScale() {
  return d3.scaleSequential()
    .domain([0, 1])
    .interpolator(d3.interpolate('#a8e6d8', '#1a7a5e'))
}

/**
 * Color scale for eviction count.
 * Uses Pressure/Harm palette (light pink → deep red).
 */
export function makeEvictionColorScale(maxEvictions) {
  return d3.scaleSequential()
    .domain([0, maxEvictions])
    .interpolator(d3.interpolate('#f4b8b8', '#c0392b'))
}

// ── Metric definitions (for the layer toggle UI) ──────────────────────────────
export const METRICS = [
  {
    key:       'avg_monthly_payment',
    label:     'Avg Monthly Payment',
    unit:      '/mo',
    format:    d => d == null ? 'No data' : `$${d.toLocaleString()}`,
    makeScale: makePaymentColorScale,
    palette:   'Housing Transition',
  },
  {
    key:       'avg_corp_own_rate',
    label:     'Corporate Ownership Rate',
    unit:      '',
    format:    d => d == null ? 'No data' : `${(d * 100).toFixed(1)}%`,
    makeScale: makeCorpOwnColorScale,
    palette:   'Investor Activity',
  },
  {
    key:       'total_evictions',
    label:     'Total Evictions (2020–2023)',
    unit:      '',
    format:    d => d == null ? 'No data' : d.toLocaleString(),
    makeScale: (geo) => {
      const max = d3.max(geo.features, f => f.properties.total_evictions) || 100
      return makeEvictionColorScale(max)
    },
    palette:   'Pressure / Harm',
  },
]

// ── Condo conversion data loader (kept for reference) ─────────────────────────
export async function loadCondoData() {
  const raw = await d3.csv('./data/viz2_condo_conversions_by_zip_year.csv', d => ({
    zip:                   String(d.zip).padStart(5, '0'),
    year:                  +d.post_year,
    num_conversions:       +d.num_conversions,
    total_new_condo_units: +d.total_new_condo_units,
    median_value_jump:     +d.median_value_jump,
    median_value_jump_pct: +d.median_value_jump_pct,
  }))
  return raw.filter(d => !isNaN(d.year) && !isNaN(d.num_conversions))
}
